import type { AppProps } from 'next/app';
import Head from 'next/head';
import { Fragment } from 'react';
import { Layout } from '../layout';
import '../styles/css/bootstrap.css';
import '../styles/css/responsive.css';
import '../styles/css/ui.css';
import '../styles/fonts/fontawesome/css/all.min.css';
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>Benyaan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </Fragment>
  );
}
export default MyApp;
